version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000" 
    volumes:
        - ./frontend/src:/usr/src/app

    container_name: frontend_container

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    volumes:
      - ./backend/src:/usr/src/app/src
    container_name: backend_container
